Health-Education-England/tis-trainee-credentials

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/api/IssueResource.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/PlacementDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/ProgrammeMembershipDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/TestCredentialDto.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/SignatureTestUtil.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/api/IssueResourceTest.java
Currently it is possible to send any signed data to any issue endpoint and it would be accepted. For example sending a placement to the programme membership endpoint would populate the `tisId`, `startDate` and `endDate` leaving the `programmeName` as `null`. The gateway appears to accept
null/empty/missing fields in the credential, so we must validate them ourselves to avoid any issues. In our example of sending a placement to the programme membership endpoint it would result in a seemingly valid Programme Membership credential being issued with no programme name and other field values from unrelated data.
Add validation to the issue endpoints to avoid empty fields being accepted.
TIS21-4066
TIS21-4070
TIS21-4071
TIS21-4074
> feat: add DTO validation to issue endpoints

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/PlacementDataDto.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/api/IssueResourceTest.java
A temporary relaxation of the rules until we populate this field correctly in the trainee profile.
TIS21-4073
> fix: allow placement NPN to be missing

- .aws/task-definition-template.json
- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/api/VerifyResource.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/config/CacheConfiguration.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/config/CacheProperties.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/config/GatewayProperties.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/IdentityDataDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/filter/FilterConfiguration.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/CachingDelegate.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationService.java
- src/main/resources/application.yml
- src/test/java/uk/nhs/hee/tis/trainee/credentials/api/IssueResourceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/api/VerifyResourceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/filter/FilterConfigurationTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/CachingDelegateIntegrationTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/CachingDelegateTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/GatewayServiceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationServiceTest.java
- src/test/resources/application-redis.yml
- src/test/resources/application.yml
Create an API endpoint to start the identity verification journey, the endpoint will accept and cache user identity data and then create a request URI the user can follow to provide an identity credential to the gateway.
Create a Redis caching layer, this will be used to cache data that must be available across requests. Such as identity data, client state and PKCE code verifiers. Internally generated states and nonces should be used as cache keys as appropriate.
Create a verification service which will manage the caching of required data and the generation of the URI to direct users to for verification.
Create an endpoint at `/api/verify/identity` which calls the service to start the verification flow.
TIS21-4181
TIS21-4182
> feat: create endpoint to start id verification

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/api/VerifyResource.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/GatewayService.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/api/VerifyResourceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/GatewayServiceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationServiceTest.java
When the callback is hit the provided code will be exchanged for a token, which is then compared against the previously cached identity data.
If the identity is confirmed, then a verified session identifier is cached for allowing issuing credentials later.
TIS21-4177
> feat: handle identity verification callback

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/filter/FilterConfiguration.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/filter/VerifiedSessionFilter.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/PublicKeyResolver.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/api/IssueResourceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/filter/FilterConfigurationTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/filter/VerifiedSessionFilterTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/PublicKeyResolverTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationServiceTest.java
Create a request filter that checks whether the current request has an associated verified session. If so, requests are allowed, otherwise requests will be blocked with guidance to verify the users identity via the API.
Update the VerificationService to provide the verification functionality.
TIS21-4177
TIS21-4184
> feat: create session verification filter

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/JwtService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/JwtServiceTest.java
Getting the claims from a JWT is not working if the token includes the `Bearer ` prefix. Strip any prefix before attempting to get the token's claims.
TIS21-4177
> fix: Bearer token prefix breaks JWT processing

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/PublicKeyResolver.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/PublicKeyResolverTest.java
The public key resolver expects a token header to have `x5t` set and the issuer to be `<gateway-host>`.
This works for verification tokens, but not issued tokens. Issued tokens do not include the `x5t` header and the issuer is
`<gateway-host>/issuing`.
Rewrite the `PublicKeyResolver` to use the `kid` (key id), `n` (modulus) and `e` (exponent) headers to determine the public key. The verification token's key id is formatted as `<kid><alg>` where as the issued token is simply `<kid>` so extra manipulation is needed to ensure consistent retrieval and caching of the key.
TIS21-4110
> fix: key not resolved for issued tokens

- README.md
The DB  connection is currently not configured, so logging credentials fails:
```
2023-03-01T09:14:21.440Z  INFO 1 --- [nio-8210-exec-4] u.n.h.t.t.c.service.IssuanceService      : Credential was issued successfully.
--
2023-03-01T09:14:21.440Z  INFO 1 --- [nio-8210-exec-4] u.n.h.t.t.c.service.GatewayService       : Building Token request.
2023-03-01T09:14:21.440Z  INFO 1 --- [nio-8210-exec-4] u.n.h.t.t.c.service.GatewayService       : Built Token request.
2023-03-01T09:14:21.440Z  INFO 1 --- [nio-8210-exec-4] u.n.h.t.t.c.service.GatewayService       : Sending token request.
2023-03-01T09:14:21.819Z  INFO 1 --- [nio-8210-exec-4] u.n.h.t.t.c.service.GatewayService       : Received token response.
2023-03-01T09:14:22.354Z  INFO 1 --- [nio-8210-exec-4] org.mongodb.driver.cluster …
```
> fix: DB connection param configuration

- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/CredentialType.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/PlacementCredentialDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/filter/SignedDataFilter.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/model/CredentialMetadata.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/model/ModificationMetadata.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/repository/ModificationMetadataRepository.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/api/IssueResourceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/api/VerifyResourceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/filter/FilterConfigurationTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/filter/SignedDataFilterTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationServiceTest.java
Signed data is currently trusted to always be accurate, with the signature valid for a set length of time.
Add an additional check to the `SignedDataFilter` to ensure that signed data is rejected if the underlying data was modified after signing.
Create a RevocationService function to get the last modified data for a given credential type and TIS ID combination.
TIS21-4128
TIS21-4304
> feat: invalidate signatures when data modified

- .aws/task-definition-template.json
A task role is required to give permissions for the SQS queue listeners, add a task role to the task definition template.
TIS21-4128
TIS21-4303
> chore: add task role to defintion template

- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/CredentialType.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/DeleteEventDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/PlacementCredentialDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/ProgrammeMembershipCredentialDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListener.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/event/ProgrammeMembershipEventListener.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListenerTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/event/ProgrammeMembershipEventListenerTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/GatewayServiceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationServiceTest.java
Signature invalidation requires a timestamp of the last modification
made to an piece of data.
Update the revocation service to store the timestamp of the modification
before revoking the credential. If no timestamp is given then the
current date/time should be used.
TIS21-4128
TIS21-4304
> feat: store last modified timestamp during revoke 

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/DeleteEventDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListener.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/event/ProgrammeMembershipEventListener.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListenerTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/event/ProgrammeMembershipEventListenerTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationServiceTest.java
The last modification timestamp uses the timestamp from the update message if it is available, however that can lead to incorrect behaviour depending on the delay between the update/delete occuring at source and it being received by this service.
Example theoretical timeline:
- 00:00 - record created in TIS
- 00:10 - record received by credentials service, last modified date stored
- 00:20 - record deleted in TIS and added to queues
- 00:30 - user starts issuance process, start time recorded as `00:30`
- 00:40 - delete event received by credentials service, last modified recorded, from source, as `00:20`
- 00:50 - user completes issuance service, callback compares the issuance start time `00:30` against the last modified time `00:20` and determines that the data was not stale.
By changing …
> fix: use current time for modified timestamp

- .aws/task-definition-template.json
- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/RecordDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/UpdateEventDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListener.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/event/ProgrammeMembershipEventListener.java
- src/main/resources/application.yml
- src/test/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListenerTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/event/ProgrammeMembershipEventListenerTest.java
I'm putting this up for review though I believe there is a (permissions?) issue with tis-trainee-sync getting the messages through, which might make testing on stage a bit tricky for now. It does seem to work locally though with a message like
`awslocal sqs send-message --queue-url http://localhost:4566/queue/tis-trainee-sync-local-update-placement --message-body '{"tisId":"1538788", "record":{"data":{},"metadata":{}}}'`
TIS21-4151
> feat: revoke credentials for updated records

- build.gradle
Revert "Merge pull request #45 from Health-Education-England/dependabot/gradle/org.springframework-spring-messaging-6.0.7"
This reverts commit d168dd178300439135f6155a10a63e582a529da0, reversing changes made to 50736c0eb1dfbb71a1cbc92a923472d045d4ba40.
Revert "Merge pull request #46 from Health-Education-England/dependabot/gradle/org.springframework.boot-3.0.5"
This reverts commit 50736c0eb1dfbb71a1cbc92a923472d045d4ba40, reversing changes made to e8c59c109b926a1ad24dbe66485cd316bb134172.
TIS21-SHED
> fix: revert spring dependency updates

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/config/EcsMetadataConfiguration.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/config/SentryConfiguration.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/config/EcsMetadataConfigurationTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/config/SentryConfigurationTest.java
The ECS metadata endpoint provides information about what and where an instance of this service is running. Including that information on Sentry error
captures allows easy identification of where an issue is occuring.
Update the Sentry configuration to include the ECS metadata. When not running in an ECS environment (i.e. the metadata endpoint is not provided) the Sentry reports should not include extra metadata e.g. showing
null values.
TIS21-4440
TIS21-4379
> feat: log ECS metadata with Sentry

- build.gradle
- src/main/resources/application.yml
The gateway endpoints have been changed, as a result the `aud` used in the tokens must be changed too.
TIS21-4545
> fix: gateway issuer audience

- build.gradle
Reverts Health-Education-England/tis-trainee-credentials#73
We'll need to investigate a fix for this, but probably better just to revert for now.
> Revert "chore(deps): bump sentryVersion from 6.19.1 to 6.20.0"

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationServiceTest.java
The identity verification is currently case sensitive, the identity credentials being used for UAT are all upper case. Relax our verification to accept any casing for the identity credential.
This may need reviewing later, but it seems a safe enough change to make.
TIS21-SHED
> fix: make identity verification case insensitive

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationService.java
Revocation is done via event, rather than API call. Currently the SQS messages do not include suitable data to allow full tracing, a later piece of work will look at how we can support XRay across our event based workflows.
TIS21-4226
> fix: disable XRay tracing on revocation

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/model/CredentialMetadata.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/IssuanceServiceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationServiceTest.java
When a credential is revoked the held metadata for that credential is deleted. Instead the metadata should be updated with a timestamp for when the revocation occured.
TIS21-5132
TIS21-5112
> feat: record revoked credentials

- .aws/task-definition-template.json
The Spring Boot built image does not contain curl, add a sidecar instance of `alpine/curl` to perform the healthcheck endpoint calls.
TIS21-SHED
> chore: move healthcheck to sidecar

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationServiceTest.java
Currently the revocation service will attempt to revoke a credential that has already been revoked.
Add a filter to ensure that revoked credentials are not attempted to be revoked again.
TIS21-5132
TIS21-5112
> fix: only revoke active credentials

- .aws/task-definition-template.json
- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/CredentialEventDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/CredentialType.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/mapper/CredentialEventMapper.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/EventPublishingService.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationService.java
- src/main/resources/application.yml
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/EventPublishingServiceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationServiceTest.java
When a credential is revoked a credential event should be published to allow other services, such as notifications, to act accordingly.
Create an EventPublishingService to handle to publish to SNS, the group ID should be set to the credential's ID to allow better de-duplication and ensure that we cannot ever get multiple downstream instances processing events for the same credential simultaneously.
TIS21-5115
TIS21-5133
> feat: emit cred event after revocation

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/GatewayService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/GatewayServiceTest.java
The PAR request previously defaulted the `response_type` and `response_mode` values, but they are now required parameters. The only valid values are the previous default of `code` and `query` respectively.
Update the PAR request to include the missing parameters.
TIS21-5232
> fix: PAR request missing required params

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/CredentialEventDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/EventPublishingService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/EventPublishingServiceTest.java
Include the `issuedAt` and `revokedAt` values when publishing credential events.
TIS21-5115
> feat: include issue/revoke timestamps in events

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/IssueResponseDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/mapper/CredentialMetadataMapper.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/model/CredentialMetadata.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/CredentialMetadataService.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/IssuanceService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/CredentialMetadataServiceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/IssuanceServiceTest.java
The expiration record against the credential metadata is not the credential expiration and is instead the expiration of the token provided with the credential data.
The real expiration date is not currently available, so the `expiresAt` field should be removed to avoid confusion.
Some additional boy scouting of the `CredentialMetadataService` tests.
TIS21-5263
TIS21-5325
> feat: remove expiresAt from credential metadata

- build.gradle
- src/main/java/uk/nhs/hee/tis/trainee/credentials/api/VerifyResource.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationService.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/api/VerifyResourceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/VerificationServiceTest.java
Currently any error messages returned to the verification callback are ignored.
Update the verification endpoint and service to include the failure reason in the redirect URL, allowing the client to display the message instead of a generic error screen.
TIS21-4778
TIS21-5502
> feat: handle verification callback errors

- build.gradle.kts
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/PlacementCredentialDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/ProgrammeMembershipCredentialDto.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListener.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/event/ProgrammeMembershipEventListener.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/model/CredentialMetadata.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationService.java
- src/main/java/uk/nhs/hee/tis/trainee/credentials/utill/Md5Hash.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListenerTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/event/ProgrammeMembershipEventListenerTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationServiceTest.java
- src/test/java/uk/nhs/hee/tis/trainee/credentials/utill/TestMd5Hash.java
> feat: Implimentation for revoking only when data in wallet changes
