src/main/resources/application.yml

fix: change port to 8210

---

.aws/task-definition-template.json

The task definition needs access needs to set several secrets for gateway functionality.
TIS21-4066
TIS21-4070

build: add gateway secrets to task definition

---

.aws/task-definition-template.json

chore: fix parameter naming

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/credentials/api/IssueResource.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/PlacementDto.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/api/IssueResourceTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/service/GatewayServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/service/JwtServiceTest.java

The fields included in the placement credential are still subject to confirmation.
TIS21-4071: Send placement data to DSP gateway

feat: add placement credential endpoint

---

.aws/task-definition-template.json

chore: add verify redirect URI to task definition

---

.aws/task-definition-template.json

build: pass database connection details

---

.aws/task-definition-template.json
build.gradle
src/main/java/uk/nhs/hee/tis/trainee/credentials/config/AmazonSqsConfig.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/config/EventQueueProperties.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/config/GatewayProperties.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/DeleteEventDto.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/event/ProgrammeMembershipEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/service/GatewayService.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationService.java
src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
src/main/resources/application.yml
src/test/java/uk/nhs/hee/tis/trainee/credentials/TisTraineeCredentialsApplicationTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/event/ProgrammeMembershipEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/service/CachingDelegateIntegrationTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/service/GatewayServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/service/PublicKeyResolverTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationServiceTest.java

feat: revoke credentials on delete events

---

src/main/java/uk/nhs/hee/tis/trainee/credentials/service/IssuanceService.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/service/RevocationService.java

fix: add some additional issue callback logging

---

build.gradle
src/main/resources/application.yml

fix: update specified DSP Gateway endpoints

---

build.gradle

Reverts Health-Education-England/tis-trainee-credentials#67

Revert "chore(deps): bump org.springframework.boot from 3.0.6 to 3.1.0"

---

build.gradle
src/main/resources/application.yml

fix: redis ssl configuration

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/PlacementCredentialDto.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/ProgrammeMembershipCredentialDto.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/mapper/CredentialDataMapper.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/mapper/CredentialDataMapperTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/service/GatewayServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/service/IssuanceServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/service/JwtServiceTest.java

feat: credential metadata

---

build.gradle

Reverts Health-Education-England/tis-trainee-credentials#106

Revert "chore(deps): bump org.springframework.boot from 3.1.3 to 3.1.4"

---

.aws/task-definition-template.json

chore: add actuator healthcheck to task def

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/credentials/api/PlacementResource.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/api/ProgrammeResource.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/api/util/AuthTokenUtil.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/dto/CredentialMetadataDto.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/mapper/CredentialMetadataMapper.java
src/main/java/uk/nhs/hee/tis/trainee/credentials/service/CredentialMetadataService.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/TestJwtUtil.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/api/PlacementResourceTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/api/ProgrammeResourceTest.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/service/CredentialMetadataServiceTest.java

add api endpoint for latest programme credential

---

build.gradle
src/main/resources/application.yml

fix: allow AWS endpoint to be overwritten

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/credentials/api/ProgrammeResource.java

Change the `/api/programme` endpoint to `/api/programme-membership` to remain consistent with the existing issue PM endpoint.
TIS21-5112

refactor: change Programme endpoint to PM

---

src/main/java/uk/nhs/hee/tis/trainee/credentials/api/ProgrammeMembershipResource.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/api/ProgrammeMembershipResourceTest.java

The PM resource tests have the wrong API path.
TIS21-5115

test: fix PM resource test

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/credentials/api/VerifyResource.java

When the verification is cancelled or fails, the error message is returned with no code.
TIS21-5502
TIS21-4778

fix: make verify callback code optional

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListener.java
src/test/java/uk/nhs/hee/tis/trainee/credentials/event/PlacementEventListenerTest.java

when testing on stage a discrepancy between the start date and end date names was discovered.

refactor: update placement fields for start date and end date
